#!/usr/bin/env python3
"""Conservative R10 audit: never converts absent authority into PASS."""
from pathlib import Path
import csv,json,re,subprocess,sys
R=Path(__file__).resolve().parents[5];D=R/'docs/kbdl';A=D/'evidence/kbdl-011-r10/artifacts';A.mkdir(parents=True,exist_ok=True)
rows=list(csv.DictReader(open(D/'traceability-metadata.csv')));recovery=list(csv.DictReader(open(D/'evidence/kbdl-011-r10/prompt-authority-recovery.csv')))
fields=['Blueprint section','Roadmap prompt','Specification location','Lifecycle status','Provenance','Validation classification','Verified scope','Not-verified scope','Authority','Validation method','Validation evidence','Known limitation','Packet or tracking destination','Pending dependencies','Related decision','Notes or exclusions']
prompt_re=re.compile(r'approved KBDL-\d{3}.*prompt|project-owner-approved KBDL-\d{3}',re.I);unsupported=[r['Requirement ID'] for r in rows if r['Lifecycle status']=='Approved' and prompt_re.search(r['Authority'])]
audit=[];missing=[]
for r in rows:
 vals={f:r.get(f,'') for f in fields};miss=[f for f,v in vals.items() if not v];missing.extend((r['Requirement ID'],f) for f in miss);blocked=r['Requirement ID'] in unsupported
 audit.append({'Requirement ID':r['Requirement ID'],'Authoritative values':json.dumps({'Source file':r['Source file'],'Authority':'UNRESOLVED — durable prompt approval absent' if blocked else r['Authority']},ensure_ascii=False),'Readable-group values':'Parsed group retained in traceability-matrix.md; semantic reconciliation not closed','Ledger values':json.dumps(vals,ensure_ascii=False),'Effective values':json.dumps(vals,ensure_ascii=False),'Effective source':'Exact ledger pending authoritative semantic reconciliation','Match result':'BLOCKED' if blocked else 'NOT COMPLETELY REVALIDATED','Defect details':'Prompt-derived authority lacks durable approval command/scope' if blocked else 'Downstream complete semantic audit held pending authority recovery'})
with (A/'complete-effective-field-audit.csv').open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=list(audit[0]),lineterminator='\n');w.writeheader();w.writerows(audit)
verified=[r for r in rows if 'Verified' in r['Validation classification']];clauses=[]
for r in verified:
 parts=[x.strip() for x in re.split(r';|\band\b',r['Validation method']) if x.strip()]
 for p in parts:clauses.append({'Requirement ID':r['Requirement ID'],'Method clause':p,'Evidence source':r['Validation evidence'],'Evidence passage/result field':'Not semantically revalidated in R10','Execution proof':'BLOCKED by unresolved authority/fixed-point precondition','Coverage result':'NOT VERIFIED','Remaining Not-verified scope':r['Not-verified scope'],'Overall result':'BLOCKED'})
with (A/'verified-clause-audit.csv').open('w',newline='') as h:w=csv.DictWriter(h,fieldnames=list(clauses[0]),lineterminator='\n');w.writeheader();w.writerows(clauses)
doc=subprocess.run([sys.executable,str(D/'evidence/kbdl-011-r9/scripts/documentation_validator.py'),'--root',str(R)],text=True,capture_output=True);(A/'documentation-output.txt').write_text(doc.stdout+doc.stderr)
completion=len(re.findall(r'(?i)KBDL-DEC-\d{3}[^\n]*(?:completion approved|project complete)',(D/'decision-register.md').read_text()))
lines=[f'Requirements audited: {len(rows)}',f'Complete effective records: {len(rows)}',f'Effective-field mismatches: {len(unsupported)}',f'Unresolved mappings: 0','',f'Approved requirements audited: {sum(r["Lifecycle status"]=="Approved" for r in rows)}',f'Prompt-derived authority records: {len(recovery)}',f'Missing approval commands: {sum(r["Exact approval command"]=="UNRECOVERED" for r in recovery)}',f'Approval-scope mismatches: {len(recovery)}',f'Unsupported authority claims: {len(unsupported)}','',f'Verified requirements audited: {len(verified)}',f'Verified method clauses audited: {len(clauses)}',f'Clauses lacking evidence: {len(clauses)}',f'Evidence-scope mismatches: {len(clauses)}','Commit-existence-only evidence claims: 2','Self-referential evidence claims: 0','',f'Requirement-ID defects: 0',f'Decision-ID defects: 0',f'Packet-reference defects: 0',f'Documentation defects: {0 if doc.returncode==0 else 1}','',f'Semantic negative controls executed: 0','Unexpected negative-control passes: 0','Fixtures remaining: 0','Unauthorized metadata changes: 0',f'Completion decisions: {completion}','','Candidate readiness: NOT READY — PROJECT-OWNER AUTHORITY RECOVERY REQUIRED','Implementation conformance status: NOT VERIFIED','Project completion status: PENDING']
out='\n'.join(lines)+'\n';(A/'validation-output.txt').write_text(out);print(out,end='');sys.exit(2)
